version: '3.9'

services:
  mongodb:
    image: mongo:4.4.11-rc1-focal
    ports:
      - "27017:27017"
    volumes:
      - .:/opt/app/data

  app:
    build: .
    links:
      - mongodb
    ports:
      - "8888:8888"
